### ISSUE TITLE
how to add dependancy for 1.2

### ISSUE THREAD

**Issue by isayed** [romanvm/kodi.web-pdb#1]
in a very simple hello-world addon
https://github.com/zag2me/script.hello.world 
i tried adding the line `<import` addon="script.module.web-pdb" `version="1.0"/>`
inside `<requires>` but it fails when trying to load the hello world addon..
i also tried changing to version="1.2" still no difference
what am i doing wrong?!
thanks!

**Comment by romanvm** [comment]
`version` property specifies **minimal** required version, so any version above that is compatible. As for your problem, I cannot tell anything without a full Kodi debug log.

**Comment by romanvm** [comment]
Since not further information has been provided, I'm closing this issue.

**Comment by Protocol-X** [comment]
I had a similar issue, the fix was kodi needs a restart if you install the zip as a stand alone and then edit the addon.xml. My guess is addon.xml is loaded only on start or install.   I can not confirm this is the users problem, but it is what I experienced.
