### ISSUE TITLE
cannot debug into some specially called funciton

### ISSUE THREAD

**Issue by tingjhenjiang** [romanvm/kodi.web-pdb#11]
Hello, thanks for your awesome work!

When I use your PDB debugger, I noticed that in some cases debugger cannot run into deeper functions.

I set up breakpoints at each line of the following code:

```
resultlist = xbmc.executebuiltin("RunScript(script.module.uepg,json=%s&refresh_path=%s&refresh_interval=%s)" % (
	urllib.quote_plus(epgsrcdict),
	urllib.quote_plus('plugin://plugin.video.hamivideo/epgjson/'), #sys.argv[0]
	urllib.quote_plus(json.dumps(7200))
	) )
return resultlist
```
The deeper-function debugging result is however limited to urllib.quote_plus functions, neither the 
"xbmc.executebuiltin" part nor the "RunScript" part.

FYI.
It would be much better if your debugger provide this functions.

**Comment by romanvm** [comment]
A Python debugger (any) can only debug Python code. Using it for debugging binary executable code (that Kodi API classes and functions are) is not possible.
