### ISSUE TITLE
View resizing "Enhancement request"

### ISSUE THREAD

**Issue by Protocol-X** [romanvm/kodi.web-pdb#2]
Can you please add handles or a view container to the html file so that the 4 windows can be resized on demand?

Thanks

**Comment by romanvm** [comment]
My front-end skills are limited, but I'll see what can be done.

**Comment by Protocol-X** [comment]
I see you are using jquery.   Maybe this will help. https://jqueryui.com/resizable/

**Comment by romanvm** [comment]
Resizing one element is not a problem, you don't even need JavaScript for that. But to make elements resizable so that not to break the whole layout is another thing.

And, honestly, I don't quite see a point in resizing. If you need to see the value of a complex variable, use `pp` command.

**Comment by Protocol-X** [comment]
Hey, was just a suggestion.   There is obviously value if someone asks for an enhancement.  Forget about it, was just offering some info since you stated it was not your strong suit.

**Comment by romanvm** [comment]
This is a free-time project and before I invest my personal time and resources into adding some feature, I need to understand its value beyond just "why not?".
