### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by h1pp0** [romanvm/kodi.web-pdb#3]
Hello,

I'm trying to do a remote debug session for an addon and unfortunately web-pdb always errors out when trying to decode data returned from the mentioned addon:

> 15:46:45.220 T:1432351648   ERROR: Traceback (most recent call last):
>                                               File "/storage/.kodi/addons/script.module.bottle/lib/bottle.py", line 862, in _handle
>                                                 return route.call(**args)
>                                               File "/storage/.kodi/addons/script.module.bottle/lib/bottle.py", line 1732, in wrapper
>                                                 rv = callback(*a, **ka)
>                                               File "/storage/.kodi/addons/script.module.web-pdb/libs/web_pdb/wsgi_app.py", line 49, in wrapper
>                                                 result = func(*args, **kwargs)
>                                               File "/storage/.kodi/addons/script.module.web-pdb/libs/web_pdb/wsgi_app.py", line 93, in send
>                                                 return json.dumps(body)
>                                               File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
>                                               File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
>                                               File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
>                                             UnicodeDecodeError: 'utf8' codec can't decode byte 0xd1 in position 11396: invalid continuation byte
> 

Not to familiar with python or debugging so I cannot provide the original input that caused it to crash.

**Comment by romanvm** [comment]
To diagnose this issue I need full information: your addon code and the exact sequence of actions that leads to this error.

**Comment by h1pp0** [comment]
I was debugging the dramafever addon located here:
http://kodi-addons.club/addon/plugin.video.dramafever/0.4.0

Only code I changed was to insert was "web_pdb.set_trace()" at line 72 of the addon.py file and select any category to trigger the breakpoint.

**Comment by romanvm** [comment]
I haven't been able to reproduce your issue. At least a quick test on Kodi 16 on Windows revealed no problems.

**Comment by h1pp0** [comment]
I'm using Kodi 17.3 on a raspberry pi 3

**Comment by romanvm** [comment]
The same, only on Pi 2 - the debugger works as expected with the plugin from your link.

**Comment by h1pp0** [comment]
I guess close the issue since it's not replicate and probably an issue with my specific setup
