### ISSUE TITLE
No module named web_pdb

### ISSUE THREAD

**Issue by diaagi** [romanvm/kodi.web-pdb#4]
Hello,
I am new to Python!
I am not able to run web_pdb, I have followed these 2 steps:
-> add <import addon="script.module.web-pdb"/> in my module addon.xml under test (CatchUpTV)
-> add import web_pdb; web_pdb.set_trace() in my module addon.py

I am with Kodi Krypton, under Windows10.
web_pdb: 1.3.2, from Official Kodi repository

I see the plugins in my install folder:
C:\Users\***\AppData\Roaming\Kodi\addons\script.module.web-pdb

The log:
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named web_pdb
                                            Traceback (most recent call last):
                                              File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\addon.py", line 30, in <module>
                                                import web_pdb; web_pdb.set_trace()
                                            ImportError: No module named web_pdb
                                            -->End of Python script error report<--
ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/) failed

It seems the module import name (web_pdb) is incorrect, right?
How is defined the module name in Python, I am looking in my Kodi addon install directory after a web_pdb.py without success.

Could you help me to correct my settings?

Thanks,

**Comment by romanvm** [comment]
Everything is correct. If you edited `addon.xml` while Kodi is running, you need to restart Kodi to re-read addon dependencies.

**Comment by diaagi** [comment]
thank you!
It works... I didn't restart kodi...!

**Comment by kampanita** [comment]
I'm having the same issue.
I'm running Kodi 17.3 Krypton, have installed web-pdb script, i can see the addon installed, when i run it, it displays a message with info about debugger. 
I have added it to addon.xml <required> section, restarted Kodi for refreshing dependencies...
But when i run my addon it says that "can not find web-pdb library" ... i'm stucked here.
