### ISSUE TITLE
Question: Is this add-on working with Libreelec?

### ISSUE THREAD

**Issue by kneespan** [romanvm/kodi.web-pdb#9]
Hi

Question, not an issue: Is this add-on working with Kodi within Libreelec 8.2.5 on Raspberry?

Thanks.

**Comment by romanvm** [comment]
Yes. The Python code is generic and does not include anything platform-specific.

**Comment by kneespan** [comment]
Thank you - that's great!
What I'm trying to do is to debug the https://github.com/aqw/xbmc-gamepass
When I add <import addon="script.module.web-pdb" /> to the addon.xml I get an error when trying to install the add-on. Do I have to install it first, and only then change the addon.xml?

Thanks.

**Comment by romanvm** [comment]
I'm not sure what you are doing but yes, both addons need to be installed in Kodi. Also please check the Readme.

**Comment by kneespan** [comment]
Worked, thank you. Can be closed. Thanks Roman.
